# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enviroment.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import sys  # We need sys so that we can pass argv to QApplication
import os
import numpy as np
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPalette,QColor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Plotters = pg.PlotWidget(self.centralwidget)
        self.Plotters.setGeometry(QtCore.QRect(30, 20, 1061, 491))
        self.Plotters.setObjectName("widget")

        # data creation
        hour = np.linspace(1, 10, num=10)
        temperature = np.random.rand(10)

        pen = pg.mkPen(color=(255, 255, 255), width=5)
        self.Plotters.plot(hour, temperature, pen=pen, symbol='o', symbolBrush=('w'), symbolSize=15)

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 530, 1061, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Pressure_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.Pressure_box.setObjectName("Pressure_box")
        self.horizontalLayout.addWidget(self.Pressure_box)
        self.Temp_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.Temp_box.setObjectName("Temp_box")
        self.horizontalLayout.addWidget(self.Temp_box)
        self.Humidity_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.Humidity_box.setObjectName("Humidity_box")
        self.horizontalLayout.addWidget(self.Humidity_box)
        self.UVA_Intensity_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.UVA_Intensity_box.setObjectName("UVA_Intensity_box")
        self.horizontalLayout.addWidget(self.UVA_Intensity_box)
        self.UVB_Intesity_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.UVB_Intesity_box.setObjectName("UVB_Intesity_box")
        self.horizontalLayout.addWidget(self.UVB_Intesity_box)
        self.UVIndex_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.UVIndex_box.setObjectName("UVIndex_box")
        self.horizontalLayout.addWidget(self.UVIndex_box)
        self.LightIntens_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.LightIntens_box.setObjectName("LightIntens_box")
        self.horizontalLayout.addWidget(self.LightIntens_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menubar.setObjectName("menubar")
        self.menuGraphs = QtWidgets.QMenu(self.menubar)
        self.menuGraphs.setObjectName("menuGraphs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuGraphs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Pressure_box.setText(_translate("MainWindow", "Pressure"))
        self.Temp_box.setText(_translate("MainWindow", "Temperature"))
        self.Humidity_box.setText(_translate("MainWindow", "Humidity"))
        self.UVA_Intensity_box.setText(_translate("MainWindow", "UVA Intensity"))
        self.UVB_Intesity_box.setText(_translate("MainWindow", "UVB Intensity"))
        self.UVIndex_box.setText(_translate("MainWindow", "UV Index"))
        self.LightIntens_box.setText(_translate("MainWindow", "Light Intensity"))
        self.menuGraphs.setTitle(_translate("MainWindow", "Graphs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
